import Navbar from "@/components/shared/navbar/navbar";
import { ContextProvider } from "@/provider/context-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ContextProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <div className="w-full relative">
            <div className="fixed top-0 left-0 w-full z-[10] ">
              <Navbar />
            </div>
            {children}
          </div>
        </body>
      </html>
    </ContextProvider>
  );
}
